apiVersion: v1
kind: ConfigMap
metadata:
  namespace: metallb-system
  name: config
data:
  config: |
    address-pools:
    - name: local
      protocol: layer2
      addresses:
      - 192.168.86.34
      - 192.168.86.39
      - 192.168.86.45
      - 192.168.86.49
      - 192.168.86.50
      - 192.168.86.53
      - 192.168.86.55