apiVersion: apps/v1
kind: Deployment
metadata:
  name: heimdall
  namespace: media
spec:
  selector:
    matchLabels:
      app: heimdall
  template:
    metadata:
      labels:
        app: heimdall
    spec:
      containers:
      - name: heimdall
        image: linuxserver/heimdall:arm64v8-latest
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        env:
          - name: PUID
            value: "1000"
          - name: PGID
            value: "1000"
          - name: TZ
            value: America/New_York
        volumeMounts:
          - mountPath: /config
            name: heimdall-config
      volumes:
        - name: heimdall-config
          hostPath:
            path: /media/config/heimdall