apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: heimdall-ingrt
  namespace: media
  labels:
    name: heimdall-ingrt
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: web
    traefik.ingress.kubernetes.io/router..tls: "false"
spec:
  entryPoints: 
    - web
    - websecure
  routes:
    - match: Host(`smrtrock.com`) && PathPrefix(`/home`)
      kind: Rule
      services:
        - name: heimdall-svc
          port: web