apiVersion: v1
kind: PersistentVolume
metadata:
  name: "media"
  labels:
    type: "local"
spec:
  storageClassName: "manual"
  capacity:
    storage: "7.28Ti"
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "/media/media"
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: "config"
  labels:
    type: "local"
spec:
  storageClassName: "manual"
  capacity:
    storage: "3.64Ti"
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "/media/config"
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: "downloads"
  labels:
    type: "local"
spec:
  storageClassName: "manual"
  capacity:
    storage: "3.64Ti"
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "/media/downloads"