---
- name: uninstall nodes
  ansible.builtin.shell: /usr/local/bin/k3s-agent-uninstall.sh
  hosts: node

- name: uninstall master
  ansible.builtin.shell: /usr/local/bin/k3s-uninstall.sh 
  hosts: master