- name: check if uninstall script exists
  stat:
    path: /usr/local/bin/k3s-agent-uninstall.sh
  register: uninstall 
- name: uninstall k3s
  command: sh /usr/local/bin/k3s-agent-uninstall.sh
  when: uninstall.stat.exists == True