---

- hosts: master
  gather_facts: yes
  become: yes
  roles:
    - role: reset/master

- hosts: node
  gather_facts: yes
  become: yes
  roles:
  - role: reset/node

- hosts: k3s_cluster
  gather_facts: yes
  become: yes
  roles:
  - role: reset/docker
  - role: reset/common
