- name: Install k3s and helm
  include_tasks: install_k3s.yml

- name: Configure k3s Token
  include_tasks: configure_k3s_token.yml


# - name: Copy K3s service file
#   register: k3s_service
#   template:
#     src: "k3s.service.j2"
#     dest: "{{ systemd_dir }}/k3s.service"
#     owner: root
#     group: root
#     mode: 0644

# - name: Enable and check K3s service
#   systemd:
#     name: k3s
#     daemon_reload: yes
#     state: restarted
#     enabled: yes
