apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: lab-cert
  namespace: cert-manager
spec:
  secretName: lab-cert-secret
  isCA: true
  commonName: '*.smrtrock.com'
  dnsNames:
    - smrtrock.com
    - '*.smrtrock.com'
  privateKey:
    size: 2048
    algorithm: RSA
  issuerRef:
    name: cluster-ca-issuer
    kind: ClusterIssuer