version: '3'
services:
  app:
    image: 'arm64v8/nginx'
    restart: always
    hostname: app
    container_name: app
    ports:
      - '80:80'
      - '81:81'
      - '443:443'
    environment:
      DB_MYSQL_HOST: "db"
      DB_MYSQL_PORT: 3306
      DB_MYSQL_USER: "myadmin"
      DB_MYSQL_PASSWORD: "LKFern13!@#"
      DB_MYSQL_NAME: "k3s"
    volumes:
      - ./data:/data
      - ./letsencrypt:/etc/letsencrypt
  db:
    image: 'arm64v8/mariadb'
    hostname: db
    container_name: db
    restart: always
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: 'LKFern13!'
      MYSQL_DATABASE: 'k3s'
      MYSQL_USER: 'myadmin'
      MYSQL_PASSWORD: 'LKFern13!@#'
    volumes:
      - ./data/mysql:/var/lib/mysql